[package]
name = "neon_bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "neon_bin"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
neon_core = { path = "../neon_core" }
rustyline = "15.0.0"
